==> Vault Proxy started! Log data will stream in below:

==> Vault Proxy configuration:

           Api Address 1: http://127.0.0.1:8101
                     Cgo: disabled
               Log Level: TRACE
                 Version: Vault v1.17.2+ent, built 2024-07-05T15:19:27Z
             Version Sha: 023471f83b7698e89424be66ed2ac8e5dad5fecc

2024-07-12T22:43:32.067+0800 [INFO]  proxy.cache: cache configured: cache_static_secrets=true disable_caching_dynamic_secrets=false
2024-07-12T22:43:32.068+0800 [DEBUG] proxy.apiproxy: configuring inmem auto-auth sink
2024-07-12T22:43:32.068+0800 [DEBUG] proxy: would have sent systemd notification (systemd not present): notification=READY=1
2024-07-12T22:43:32.068+0800 [INFO]  proxy.cache.staticsecretcacheupdater: starting static secret cache updater subsystem
2024-07-12T22:43:32.068+0800 [INFO]  proxy.sink.server: starting sink server
2024-07-12T22:43:32.068+0800 [INFO]  proxy.auth.handler: starting auth handler
2024-07-12T22:43:32.068+0800 [INFO]  proxy.auth.handler: authenticating
2024-07-12T22:43:32.070+0800 [INFO]  proxy.auth.handler: authentication successful, sending token to sinks
2024-07-12T22:43:32.070+0800 [INFO]  proxy.auth.handler: starting renewal process
2024-07-12T22:43:32.070+0800 [DEBUG] proxy.cache.leasecache: storing auto-auth token into the cache
2024-07-12T22:43:32.070+0800 [TRACE] proxy.cache.leasecache: auto-auth token already exists in cache; no need to store it again
2024-07-12T22:43:32.071+0800 [INFO]  proxy.auth.handler: renewed auth token
2024-07-12T22:43:32.173+0800 [DEBUG] proxy.cache.staticsecretcacheupdater: starting pre-event stream update of static secrets
2024-07-12T22:43:32.173+0800 [DEBUG] proxy.cache.staticsecretcacheupdater: finished pre-event stream update of static secrets
2024-07-12T22:44:14.795+0800 [INFO]  proxy.auth.handler: renewed auth token
2024-07-12T22:44:33.707+0800 [ERROR] proxy.cache.staticsecretcacheupdater: error occurred during streaming static secret cache update events: err="error when attempting to read from event stream, reopening websocket: failed to get reader: failed to read frame header: EOF"
2024-07-12T22:44:43.711+0800 [ERROR] proxy.cache.staticsecretcacheupdater: error occurred during streaming static secret cache update events: err="error returned when opening event stream web socket to ws://127.0.0.1:8200/v1/sys/events/subscribe/kv%2A?json=true, ensure auto-auth token has correct permissions and Vault is Enterprise version 1.16 or above: failed to WebSocket dial: failed to send handshake request: Get \"http://127.0.0.1:8200/v1/sys/events/subscribe/kv%2A?json=true\": dial tcp 127.0.0.1:8200: connect: connection refused"
2024-07-12T22:44:53.715+0800 [ERROR] proxy.cache.staticsecretcacheupdater: error occurred during streaming static secret cache update events: err="error returned when opening event stream web socket to ws://127.0.0.1:8200/v1/sys/events/subscribe/kv%2A?json=true, ensure auto-auth token has correct permissions and Vault is Enterprise version 1.16 or above: failed to WebSocket dial: failed to send handshake request: Get \"http://127.0.0.1:8200/v1/sys/events/subscribe/kv%2A?json=true\": dial tcp 127.0.0.1:8200: connect: connection refused"
2024-07-12T22:45:03.072+0800 [INFO]  proxy.auth.handler: lifetime watcher done channel triggered, re-authenticating
2024-07-12T22:45:03.719+0800 [ERROR] proxy.cache.staticsecretcacheupdater: error occurred during streaming static secret cache update events: err="error returned when opening event stream web socket to ws://127.0.0.1:8200/v1/sys/events/subscribe/kv%2A?json=true, ensure auto-auth token has correct permissions and Vault is Enterprise version 1.16 or above: failed to WebSocket dial: failed to send handshake request: Get \"http://127.0.0.1:8200/v1/sys/events/subscribe/kv%2A?json=true\": dial tcp 127.0.0.1:8200: connect: connection refused"
2024-07-12T22:45:04.073+0800 [INFO]  proxy.auth.handler: authenticating
2024-07-12T22:45:04.074+0800 [ERROR] proxy.auth.handler: error authenticating: error="Put \"http://127.0.0.1:8200/v1/auth/approle/login\": dial tcp 127.0.0.1:8200: connect: connection refused" backoff=760ms
2024-07-12T22:45:04.835+0800 [INFO]  proxy.auth.handler: authenticating
2024-07-12T22:45:04.836+0800 [ERROR] proxy.auth.handler: error authenticating: error="Put \"http://127.0.0.1:8200/v1/auth/approle/login\": dial tcp 127.0.0.1:8200: connect: connection refused" backoff=760ms
2024-07-12T22:45:06.341+0800 [INFO]  proxy.auth.handler: authenticating
2024-07-12T22:45:06.341+0800 [ERROR] proxy.auth.handler: error authenticating: error="Put \"http://127.0.0.1:8200/v1/auth/approle/login\": dial tcp 127.0.0.1:8200: connect: connection refused" backoff=1.5s
